### ISSUE TITLE
STCP映射隧道 start error: SakuraFrp API Error (Status: 404, Text: 404 Proxy not found)

### ISSUE THREAD

**Issue by KJZH001** [ZeroDream-CN/SakuraPanel#11]
## 问题描述
启动STCP隧道后返回404错误

## 截图示列
![QQ浏览器截图20201114212603.png](https://icdn.7t5j.cn/2020/11/14/a864864fbb879.png)
![QQ浏览器截图20201114212457.png](https://icdn.7t5j.cn/2020/11/14/c14031342e995.png)

## 配置文件(已经删去部分敏感内容)
frps

```
[common]
# Frp 绑定地址，默认 0.0.0.0 无需修改
bind_addr = 0.0.0.0

# Frp 运行端口
bind_port = 30003

# Kcp 模式运行端口，需要和上面的相同
kcp_bind_port = 30003

# 管理端口，默认 8233
dashboard_port = 

# 管理用户名，必须是 admin
dashboard_user = admin

# 管理密码
dashboard_pwd = 

# HTTP 映射端口
vhost_http_port = 80

# HTTPS 映射端口
vhost_https_port = 443

# Frp 服务器日志
# log_file = ./frps.log

# Frp Token 特权密码
token = 

# UDP 穿透端口
bind_udp_port = 7001

# 以下项目无需修改
max_pool_count = 50
tcp_mux = true
authentication_timeout = 0
log_level = debug
log_max_days = 3

# 是否启用 Api 功能
api_enable = true

# Api 服务器地址
api_baseurl = http://网址已经去除/api/

# Api 密码
api_token = 

```

frpc

```
[common]
server_addr = 
server_port = 30003
tcp_mux = true
protocol = tcp
user =
token = 
dns_server = 114.114.114.114
 
[AliyunRdp]
privilege_mode = true
type = tcp
local_ip = 127.0.0.1
local_port = 3389
remote_port = 
use_encryption = true
use_compression = true

[StcpAliyunMysql]
privilege_mode = true
type = stcp
local_ip = 127.0.0.1
local_port = 3306
sk = 
use_encryption = true
use_compression = true
 
```

由于这部分相关的内容在网上几乎找不到，所以我认为这是个bug将其提交上来

如果这是由于我的疏忽导致配置文件错误导致的，还麻烦请您指出错误，我对此深感抱歉

此外，普通的TCP映射的使用时一切正常的，所以应该可以排除大部分运行时的意外故障

如果需要服务器的相应日志，请回复我，我会尽快将其通过合适的方式发送给您

**Comment by kasuganosoras** [comment]
SK（访客连接密码）不能为空

**Comment by KJZH001** [comment]
> SK（访客连接密码）不能为空

emmn...抱歉是我没讲清楚，那个sk我是发上来以后故意删掉的

这个问题我感觉可能是TCP和XTCP因为不需要远程端口所以返回API的参数出错
目前的话我自己稍微修了一下，不过我的这种修复方法可能不是很安全，所以请您参考一下

https://blog.moeworld.tech/2020/11/29/sakura-frp-404-%e9%94%99%e8%af%af%e8%a7%a3%e5%86%b3/

**Comment by kasuganosoras** [comment]
STCP 和 XTCP 其实都是支持远程端口的，只不过在添加隧道的时候没有做强制要求，这个只需要对 API 稍加修改，把 STCP 和 XTCP 单独拎出来做判断就行了，因为我之前基本上不用这两种模式，所以就习惯性把他们和 TCP UDP 放在一起判断了。

**Comment by KJZH001** [comment]
> STCP 和 XTCP 其实都是支持远程端口的，只不过在添加隧道的时候没有做强制要求，这个只需要对 API 稍加修改，把 STCP 和 XTCP 单独拎出来做判断就行了，因为我之前基本上不用这两种模式，所以就习惯性把他们和 TCP UDP 放在一起判断了。

好的，感谢您的修复和解答

此外我还有个请求不知道您能否同意呢，因为我个人比较喜欢曾经的SakuraFrp的GUI客户端，相信同样怀念的人应该也吧，所以我想问问能否将曾经的GUI客户端开源呢？

或许我这么问有些唐突了，如果您介意的话也没有关系，我在这里先向您表示深感抱歉

**Comment by kasuganosoras** [comment]
GUI 客户端其实不是我开发的，我只是做了个命令行版本的客户端，GUI 那个本质上是套壳的命令行版本。。

不过我可以问问之前 GUI 客户端的作者看看他还有没有保留源代码（我现在连他 QQ 可能都找不到了。。）

**Comment by KJZH001** [comment]
> GUI 客户端其实不是我开发的，我只是做了个命令行版本的客户端，GUI 那个本质上是套壳的命令行版本。。
> 
> 不过我可以问问之前 GUI 客户端的作者看看他还有没有保留源代码（我现在连他 QQ 可能都找不到了。。）

好的，谢谢
麻烦您了
