### ISSUE TITLE
主控被控都装好，但被控端无法根据面板设置开启穿透

### ISSUE THREAD

**Issue by a893737944** [ZeroDream-CN/SakuraPanel#24]
感谢作者的开源共享，知道项目已经停止更新，但是还是想咨询一下。

被控端启动好，看日志运行全都是200 ：
```
2022/01/16 00:21:13 [I] [dashboard_api.go:173] Http request: [/api/proxy/tcp]
2022/01/16 00:21:13 [I] [dashboard_api.go:167] Http response [/api/proxy/tcp]: code [200]
```

主控端也能检测到节点信息，没有报错。但是添加好穿透后，被控端无任何反映，依旧200。 

意思是无论添加什么穿透，节点都没反应，无法实现穿透。

**Comment by OldGodShen** [comment]
你节点的防火墙配置了吗

**Comment by a893737944** [comment]
节点防火墙应该是没启动的，检测的端口好像2333这些都是通的，还是说需要额外的配置？

**Comment by a893737944** [comment]
我是配置好网页的三个文件，其中api/index.php 那个是
`define("API_TOKEN", "这里填了APItoken");`

然后节点启动是用这个命令：
`./frps -c frps.ini`

启动后的运行日志：
`2022/01/16 10:05:16 [I] [service.go:149] frps tcp listen on 0.0.0.0:2333
2022/01/16 10:05:16 [I] [service.go:158] frps kcp listen on udp 0.0.0.0:2333
2022/01/16 10:05:16 [I] [service.go:191] http service listen on 0.0.0.0:81
2022/01/16 10:05:16 [I] [service.go:212] https service listen on 0.0.0.0:82
2022/01/16 10:05:16 [I] [service.go:231] nat hole udp service listen on 0.0.0.0:7001
2022/01/16 10:05:16 [I] [service.go:242] Dashboard listen on 0.0.0.0:8288
2022/01/16 10:05:16 [I] [root.go:204] Start frps success
2022/01/16 10:23:17 [I] [dashboard_api.go:65] Http request: [/api/serverinfo]
2022/01/16 10:23:17 [I] [dashboard_api.go:58] Http response [/api/serverinfo]: code [200]`

发现面板删除后，节点能接收到，报404：
`2022/01/16 10:45:18 [I] [dashboard_api.go:341] Http request: [/api/client/close/{user}] "eeecb85105149063"
2022/01/16 10:45:18 [I] [dashboard_api.go:339] Http response [/api/client/close/{user}]: code [404]
`

但是添加穿透依然没有任何反映。

**Comment by OldGodShen** [comment]
frps.ini里面配置了apitoken吗？
节点是否能访问主站的api
api后面的节点id是否正确？

**Comment by a893737944** [comment]
配置了的，这是frps.ini：
`# 是否启用 Api 功能
api_enable = true

# Api 服务器地址
api_baseurl = https://www.网址.cn/api/

# Api 密码（节点 ID 在面板上添加的时候可以看到）
api_token = token|2`


能够访问api的，id也正确

**Comment by OldGodShen** [comment]
是否能把frpc的报错信息发出来看看

**Comment by aisyun** [comment]
有解决的吗？能不能给个解决方法
